### ISSUE TITLE
ldapserver crash bug: panic: Expecting 0x30 as first byte, but got 0x4d instead

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor#1160]
```log
2022/09/26 12:42:49 Connection client [4] from 192.241.214.147:45002 accepted 
2022/09/26 12:42:49 client 4 close() 
2022/09/26 12:42:49 client 4 close() - stop reading from client
2022/09/26 12:42:49 client 4 close() - Abandon signal sent to processors
2022/09/26 12:42:49 client [4] request processors ended
2022/09/26 12:42:49 client [4] connection closed
panic: Expecting 0x30 as first byte, but got 0x4d instead

goroutine 20690 [running]:
github.com/forestmgy/ldapserver.readTagAndLength(0x27de25?, 0x236d6530598?)
        C:/GoPath/pkg/mod/github.com/forestmgy/ldapserver@v1.0.9/packet.go:89 +0x2b9
github.com/forestmgy/ldapserver.readLdapMessageBytes(0x30?)
        C:/GoPath/pkg/mod/github.com/forestmgy/ldapserver@v1.0.9/packet.go:54 +0x45
github.com/forestmgy/ldapserver.readMessagePacket(0x30?)
        C:/GoPath/pkg/mod/github.com/forestmgy/ldapserver@v1.0.9/packet.go:18 +0x1d
github.com/forestmgy/ldapserver.(*client).ReadPacket(0xc00016b130)
        C:/GoPath/pkg/mod/github.com/forestmgy/ldapserver@v1.0.9/client.go:58 +0x29
github.com/forestmgy/ldapserver.(*client).serve(0xc00016b130)
        C:/GoPath/pkg/mod/github.com/forestmgy/ldapserver@v1.0.9/client.go:122 +0x365
created by github.com/forestmgy/ldapserver.(*Server).serve
        C:/GoPath/pkg/mod/github.com/forestmgy/ldapserver@v1.0.9/server.go:110 +0x42a

Process finished with the exit code 2
```

![image](https://user-images.githubusercontent.com/3787410/192205090-7a8f23e4-d8a5-4b95-9b93-135c0ac98061.png)

**Comment by hsluoyz** [comment]
@forestmgy

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/pull/1161
