### ISSUE TITLE
panic: pq: trailing junk after parameter at or near "$1A"

### ISSUE THREAD

**Issue by KimJungWha** [casdoor/casdoor#1318]
hi there. I get this error when I use docker to deploy casdoor and postgresql, can anyone help me?

```bash
/ # ./server
panic: pq: trailing junk after parameter at or near "$1A"

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Adapter).createTable(0xc000498e40)
	/root/go/src/casdoor/object/adapter.go:128 +0x8ae
github.com/casdoor/casdoor/object.InitAdapter(0x0)
	/root/go/src/casdoor/object/adapter.go:53 +0xb1
main.main()
	/root/go/src/casdoor/main.go:38 +0xa5
```
**app.conf**

```apacheconf
appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
# socks5Proxy = "127.0.0.1:10808"
socks5Proxy =
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
# ldapServerPort = 389
ldapServerPort =
languages = en,zh,es,fr,de,ja,ko,ru
driverName = postgres
dataSourceName = "user=casdoor password=casdoor host=172.17.0.1 port=5432 sslmode=disable dbname=casdoor"
dbName =
```

**postgresql**

```bash
➜  casdoor psql -U casdoor -d casdoor -h 172.17.0.1
Password for user casdoor:
psql (14.5, server 15.1)
WARNING: psql major version 14, server major version 15.
         Some psql features might not work.
Type "help" for help.

casdoor=> \d
                 List of relations
 Schema |        Name         |   Type   |  Owner
--------+---------------------+----------+----------
 public | application         | table    | postgres
 public | casbin_adapter      | table    | postgres
 public | casbin_rule         | table    | postgres
 public | cert                | table    | postgres
 public | ldap                | table    | postgres
 public | model               | table    | postgres
 public | organization        | table    | postgres
 public | payment             | table    | postgres
 public | permission          | table    | postgres
 public | permission_rule     | table    | postgres
 public | product             | table    | postgres
 public | provider            | table    | postgres
 public | record              | table    | postgres
 public | record_id_seq       | sequence | postgres
 public | resource            | table    | postgres
 public | role                | table    | postgres
 public | syncer              | table    | postgres
 public | token               | table    | postgres
 public | user                | table    | postgres
 public | verification_record | table    | postgres
 public | webhook             | table    | postgres
(21 rows)

casdoor=>
```

**Comment by hsluoyz** [comment]
@forestmgy

**Comment by forestmgy** [comment]
This is because the `xorm:1.0.4` has a bug when connecting to Postgres. I have made a PR to update the xorm version
#1321
