### ISSUE TITLE
Casdoor fails, if previous database exists.

### ISSUE THREAD

**Issue by eu-erwin** [casdoor/casdoor#1520]
**Type**: Bug
**Docker Image**: latest & v1.230.0
**Driver**: Postgresql

Aside from the warning, I think the the bug, which previously fixed in https://github.com/casdoor/casdoor/pull/681.
happened again on the latest image and on v1.230.0

Restart the docker container should be able to reproduce this bug.

```
[xorm] [warn]  2023/02/03 20:59:06.863749 Table organization column theme_data db type is JSONB, struct type is JSON
2023-02-03T20:59:06.864166998Z [xorm] [warn]  2023/02/03 20:59:06.863835 Table organization column init_score db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:07.308667594Z [xorm] [warn]  2023/02/03 20:59:07.308210 Table user column score db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:07.308707683Z [xorm] [warn]  2023/02/03 20:59:07.308230 Table user column karma db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:07.308718439Z [xorm] [warn]  2023/02/03 20:59:07.308238 Table user column ranking db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:07.308727938Z [xorm] [warn]  2023/02/03 20:59:07.308318 Table user column signin_wrong_times db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:08.146893843Z [xorm] [warn]  2023/02/03 20:59:08.146797 Table casbin_adapter column port db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:08.405965875Z [xorm] [warn]  2023/02/03 20:59:08.405748 Table provider column port db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:08.660217169Z [xorm] [warn]  2023/02/03 20:59:08.660047 Table application column expire_in_hours db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:08.660260052Z [xorm] [warn]  2023/02/03 20:59:08.660064 Table application column refresh_expire_in_hours db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:08.660273881Z [xorm] [warn]  2023/02/03 20:59:08.660082 Table application column theme_data db type is JSONB, struct type is JSON
2023-02-03T20:59:08.660286243Z [xorm] [warn]  2023/02/03 20:59:08.660091 Table application column form_offset db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:08.874806931Z [xorm] [warn]  2023/02/03 20:59:08.874596 Table resource column file_size db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:09.083926697Z [xorm] [warn]  2023/02/03 20:59:09.083743 Table token column expires_in db type is BIGINT, struct type is INTEGER
2023-02-03T20:59:09.508671849Z panic: pq: column "id" of relation "record" already exists
2023-02-03T20:59:09.508723183Z 
2023-02-03T20:59:09.508735545Z goroutine 1 [running]:
2023-02-03T20:59:09.508747558Z github.com/casdoor/casdoor/object.(*Adapter).createTable(0xc0000db640)
2023-02-03T20:59:09.508758454Z 	/go/src/casdoor/object/adapter.go:183 +0x8c5
2023-02-03T20:59:09.508767533Z github.com/casdoor/casdoor/object.InitAdapter(0x0)
2023-02-03T20:59:09.508778080Z 	/go/src/casdoor/object/adapter.go:53 +0xb1
2023-02-03T20:59:09.508786181Z main.main()
2023-02-03T20:59:09.508794702Z 	/go/src/casdoor/main.go:38 +0xa7
```

**Comment by OutOfEastGate** [comment]
@eu-erwin Hi, I used docker to run postgres v15.1, casdoor v1.230.0, and then restart the container, but there is no problem you said.  It looks like you created the database tables manually, and you should only create a database named casdoor or your own name before starting casdoor.
details: https://casdoor.org/zh/docs/basic/server-installation#postgresql
I hope I can help you.

**Comment by hsluoyz** [comment]
@eu-erwin what Postgresql version do you use? Have you enabled features like auto type conversions like from INTEGER to BIGINT?

**Comment by eu-erwin** [comment]
hm, now you said it. I am not using postgresql at all, just an postgresql compatible database. It might be the issue.
I am using cockroachdb. Initially I thought, it might be the driver. But, it is possible the database isn't fully compatible with postgresql.

**Comment by hsluoyz** [comment]
@eu-erwin I think it's highly related to the XORM (the ORM we used) version. Can you locate starting from which Casdoor release this issue happens?

**Comment by ppaanngggg** [comment]
@eu-erwin  as https://www.cockroachlabs.com/docs/stable/serial.html#modes-of-operation

you can add `serial_normalization=virtual_sequence` to your `dataSourceName` conf. you need to recreate tables.

When xorm sync table will check columns and skip column with default as `unique_rowid()`

**Comment by hsluoyz** [comment]
@ppaanngggg thanks!

@eu-erwin can you try this method?

**Comment by eu-erwin** [comment]
> @ppaanngggg thanks!
> 
> @eu-erwin can you try this method?

@hsluoyz, added this argument is indeed working "serial_normalization=virtual_sequence".
Thank you, @ppaanngggg! 

For users, who use cockroachdb, changes your config like below:
```
driverName = postgres
dataSourceName = "user=**** password=**** host=**** port=26257 sslmode=disable dbname=app serial_normalization=virtual_sequence"
dbName =
```

Leave the dbName empty just like the documentation, in case you use postgres. add **serial_normalization=virtual_sequence** in the dataSourceName, like @ppaanngggg suggested.

**Comment by hsluoyz** [comment]
@eu-erwin great to see it's resolved! Can you also add it to the docs: https://casdoor.org/docs/basic/server-installation#postgresql ? Click here to fork it and make a PR

![image](https://user-images.githubusercontent.com/3787410/218887463-e4c0be7f-09d5-42d1-a86a-b8ebcd946faa.png)
