### ISSUE TITLE
bug: TypeError: this.props.onUpdateApplication is not a function

### ISSUE THREAD

**Issue by jinzhijie** [casdoor/casdoor#1551]
```
Uncaught (in promise) TypeError: this.props.onUpdateApplication is not a function
    at r.value (LoginPage.js:170:16)
    at LoginPage.js:133:18
```
https://github.com/casdoor/casdoor/blob/6beb68dccec812b6794cf7186c4ed7def0cade91/web/src/auth/LoginPage.js#L170

## Runtime
Casdoor : v1.239.0
Docker Hub image: [Image Layer Details - casbin/casdoor:v1.239.0 | Docker Hub](https://hub.docker.com/layers/casbin/casdoor/v1.239.0/images/sha256-c7b22fec1dfa2153d9b4d69fa5ed3ed66063713aaa0f5494e376cfa9fed7a64b?context=explore)

**Comment by jinzhijie** [comment]
Fix in #1549
