### ISSUE TITLE
Unknown database 'casdoor' when run casdoor-all-in-one

### ISSUE THREAD

**Issue by Ieooo** [casdoor/casdoor#1963]
I got error when running with `docker run -p 8000:8000 --rm casbin/casdoor-all-in-one:latest`
```shell
docker run -p 8000:8000 --rm casbin/casdoor-all-in-one:latest
Starting MariaDB database server: mariadbd.
panic: Error 1049: Unknown database 'casdoor'

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Adapter).createTable(0xc0002f0740)
        /go/src/casdoor/object/adapter.go:131 +0x9ee
github.com/casdoor/casdoor/object.CreateTables(0x40?)
        /go/src/casdoor/object/adapter.go:60 +0x31
main.main()
        /go/src/casdoor/main.go:38 +0xa9
```

**Comment by hsluoyz** [comment]
@Ieooo fixed by: https://github.com/casdoor/casdoor/commit/ff87c4ea33c036db6ba62064634eacca4c6fbf97
