### ISSUE TITLE
Unable to start because of `Multiple primary key defined`.

### ISSUE THREAD

**Issue by mzch** [casdoor/casdoor#1989]
Unable to start Casdoor.

```
[xorm] [warn]  2023/06/19 01:11:00.191853 Table organization has column phone_prefix but struct has not related field
[xorm] [warn]  2023/06/19 01:11:00.191885 Table organization has column password_complex_options but struct has not related field
[xorm] [warn]  2023/06/19 01:11:00.194243 Table user has column country_codes but struct has not related field
[xorm] [warn]  2023/06/19 01:11:00.195444 Table group has column id but struct has not related field
[xorm] [warn]  2023/06/19 01:11:00.195451 Table group has column parent_group_id but struct has not related field
panic: Error 1068: Multiple primary key defined

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Adapter).createTable(0xc00083d500)
        /srv/casdoor/casdoor/object/adapter.go:150 +0xa85
github.com/casdoor/casdoor/object.CreateTables(0x25?)
        /srv/casdoor/casdoor/object/adapter.go:64 +0x36
main.main()
        /srv/casdoor/casdoor/main.go:43 +0x3e
```

Go: `1.20.5`
Casdoor: `v1.342.1`

**Comment by hsluoyz** [comment]
@mzch please delete the DB table: `user_group_relation` (backup the data if still needed) and restart Casdoor again.

**Comment by mzch** [comment]
Oh, fixed! Thanks @hsluoyz ! :)
