### ISSUE TITLE
Updated version reports error "panic: Error 1068: Multiple primary key defined"

### ISSUE THREAD

**Issue by aosolao** [casdoor/casdoor#2166]
I deployed Casdoor using Docker containers. 
When I upgraded from version "casbin/casdoor:v1.375.0" to version "casbin/casdoor:v1.379.0", 
I encountered the following error during instance startup:
```
panic: Error 1068: Multiple primary key defined

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Ormer).createTable(0xc000980540)
	/go/src/casdoor/object/ormer.go:199 +0x9ae
github.com/casdoor/casdoor/object.CreateTables(0x58?)
	/go/src/casdoor/object/ormer.go:73 +0x36
main.main()
	/go/src/casdoor/main.go:43 +0x3e
```
How can I resolve this issue?

**Comment by hsluoyz** [comment]
@aosolao delete DB's `adapter` table and restart
