### ISSUE TITLE
Upgrade failure

### ISSUE THREAD

**Issue by aosolao** [casdoor/casdoor#2192]
```
[xorm] [warn]  2023/08/09 01:38:51.317137 Table adapter column port db type is VARCHAR(20), struct type is INT
[xorm] [warn]  2023/08/09 01:38:51.327909 Table provider has column custom_scope but struct has not related field
[xorm] [warn]  2023/08/09 01:38:51.378737 Table payment has column organization but struct has not related field
panic: arg port as int: strconv.ParseInt: parsing "": invalid syntax

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
	/go/src/casdoor/authz/authz.go:38 +0x153
main.main()
	/go/src/casdoor/main.go:51 +0xaa
```

Upgrading from image version image: casbin/casdoor:v1.379.0 to image: casbin/casdoor:v1.384.0 caused the above errors and startup failure.

**Comment by hsluoyz** [comment]
@aosolao delete DB's `adapter` table, restart Casdoor

**Comment by aosolao** [comment]
```
[xorm] [warn]  2023/08/09 02:39:17.697530 Table provider has column custom_scope but struct has not related field
[xorm] [warn]  2023/08/09 02:39:17.755109 Table payment has column organization but struct has not related field
panic: adapter not found

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
	/go/src/casdoor/authz/authz.go:38 +0x153
main.main()
	/go/src/casdoor/main.go:51 +0xaa

```

@hsluoyz 
Even after removing the adapter, I'm still seeing the above errors upon startup.

**Comment by hsluoyz** [comment]
@aosolao pull this commit: https://github.com/casdoor/casdoor/commit/6746551447d7df9f286025296ec4d7ccad357205 

Then fix your setting with the new improved error message
