### ISSUE TITLE
`1.388.0` can't start (panic).

### ISSUE THREAD

**Issue by mzch** [casdoor/casdoor#2210]
Updaring casdoor to `1.388.0`, the enforcer panicked.

```
[xorm] [warn]  2023/08/14 01:48:07.140032 Table organization has column phone_prefix but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.140078 Table organization has column password_complex_options but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.142106 Table user has column country_codes but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.142116 Table user has column multi_factor_auths but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.143326 Table group has column id but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.143335 Table group has column parent_group_id but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.147884 Table adapter has column model but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.147893 Table adapter has column file but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.150370 Table provider has column custom_scope but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.158936 Table syncer has column table_primary_key but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.162870 Table payment has column organization but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.163998 Table ldap has column admin but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.164008 Table ldap has column passwd but struct has not related field
[xorm] [warn]  2023/08/14 01:48:07.171099 Table pricing has column has_trial but struct has not related field
panic: the enforcer: built-in/user-enforcer-built-in is not found

goroutine 1 [running]:
github.com/casdoor/casdoor/object.InitUserManager()
        /srv/casdoor/casdoor/object/user.go:39 +0x92
main.main()
        /srv/casdoor/casdoor/main.go:52 +0x10c
```

**Comment by hsluoyz** [comment]
@mzch delete three DB tables: model, adapter and enforcer. Restart Casdoor

**Comment by mzch** [comment]
Fixed. Thanks! ;)
