### ISSUE TITLE
Unique constraint violated at initialization

### ISSUE THREAD

**Issue by urihani** [casdoor/casdoor#2366]
Hello,

I'm trying to initialize casdoor with init_data.json by injecting it in docker. After launching my container, i've got these errors:

```
goroutine 1 [running]:
2023-09-26 18:07:58 github.com/casdoor/casdoor/util.GetOwnerAndNameFromIdNoCheck(...)
2023-09-26 18:07:58     /go/src/casdoor/util/string.go:123
2023-09-26 18:07:58 github.com/casdoor/casdoor/object.GetRole({0x0?, 0xf51e0?})
2023-09-26 18:07:58     /go/src/casdoor/object/role.go:86 +0x7c
2023-09-26 18:07:58 github.com/casdoor/casdoor/object.getRolesInRole({0x0, 0x0}, 0x4000d67c48?)
2023-09-26 18:07:58     /go/src/casdoor/object/permission_enforcer.go:140 +0x2c
2023-09-26 18:07:58 github.com/casdoor/casdoor/object.getGroupingPolicies(0x40001bb680)
2023-09-26 18:07:58     /go/src/casdoor/object/permission_enforcer.go:173 +0x168
2023-09-26 18:07:58 github.com/casdoor/casdoor/object.addGroupingPolicies(0x4000d67db8?)
2023-09-26 18:07:58     /go/src/casdoor/object/permission_enforcer.go:216 +0x38
2023-09-26 18:07:58 github.com/casdoor/casdoor/object.AddPermission(0x40001bb680)
2023-09-26 18:07:58     /go/src/casdoor/object/permission.go:183 +0x68
2023-09-26 18:07:58 github.com/casdoor/casdoor/object.initDefinedPermission(0x40001bb680)
2023-09-26 18:07:58     /go/src/casdoor/object/init_data.go:314 +0xe8
2023-09-26 18:07:58 github.com/casdoor/casdoor/object.InitFromFile()
2023-09-26 18:07:58     /go/src/casdoor/object/init_data.go:74 +0x23c
2023-09-26 18:07:58 main.main()
2023-09-26 18:07:58     /go/src/casdoor/main.go:40 +0x60
2023-09-26 18:07:59 panic: pq: duplicate key value violates unique constraint "provider_pkey"
```

```
2023-09-26 18:07:59 
2023-09-26 18:07:59 goroutine 1 [running]:
2023-09-26 18:07:59 github.com/casdoor/casdoor/object.initDefinedProvider(0x4000b20780)
2023-09-26 18:07:59     /go/src/casdoor/object/init_data.go:284 +0xd0
2023-09-26 18:07:59 github.com/casdoor/casdoor/object.InitFromFile()
2023-09-26 18:07:59     /go/src/casdoor/object/init_data.go:56 +0xbc
2023-09-26 18:07:59 main.main()
2023-09-26 18:07:59     /go/src/casdoor/main.go:40 +0x60
2023-09-26 18:08:00 panic: pq: duplicate key value violates unique constraint "provider_pkey"
```

It happens even if the json file is empty.

Here is the Organizations section:
```json{
    "organizations": [
        {
            "owner": "casdoor",
            "name": "example_org",
            "displayName": "Example Organization",
            "websiteUrl": "",
            "favicon": "",
            "passwordType": "argon2id",
            "passwordSalt": "7kBf&6JphAnuk70HJ32R@TjQ+nL5mWz#",
            "passwordOptions": [
                "AtLeast8",
                "Aa123",
                "SpecialChar"
            ],
            "countryCodes": [
                "US",
                "GB",
                "ES",
                "FR",
                "DE",
                "CN",
                "JP",
                "KR",
                "VN",
                "ID",
                "SG",
                "IN",
                "IT",
                "MY",
                "TR",
                "DZ",
                "IL",
                "PH",
                "NL",
                "PL",
                "FI",
                "SE",
                "UA",
                "KZ"
            ],
            "defaultAvatar": "",
            "defaultApplication": "",
            "tags": [],
            "languages": [
                "en",
                "zh",
                "es",
                "fr",
                "de",
                "id",
                "ja",
                "ko",
                "ru",
                "vi",
                "it",
                "ms",
                "tr",
                "ar",
                "he",
                "nl",
                "pl",
                "fi",
                "sv",
                "uk",
                "kk",
                "fa"
            ],
            "masterPassword": "cjF&EC52",
            "initScore": 2000,
            "enableSoftDeletion": true,
            "isProfilePublic": true,
            "accountItems": []
        }
    ],
```

and the docker compose section:
`casdoor:
    container_name: casdoor-app
    restart: always
    image: casbin/casdoor
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8000:8000"
    depends_on:
      - casdoor-db
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/conf/
      - ./init_data.json:/init_data.json
    networks:
      - custom_network`

Thanks a lot!

**Comment by hsluoyz** [comment]
@urihani fixed by: https://github.com/casdoor/casdoor/commit/06e3b8481ff9ab2179471686e883466dc4701010

and as a note, the organization's `owner` must be hard-coded to `admin`

**Comment by urihani** [comment]
Thank you 🙂
