### ISSUE TITLE
docker运行casdoor报错panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

### ISSUE THREAD

**Issue by lywlbk** [casdoor/casdoor#3121]
详细日志如下：
`panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93
panic: Error 1280: Incorrect index name 'IDX_casbin_api_rule_v2'

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
/go/src/casdoor/authz/authz.go:32 +0x139
main.main()
/go/src/casdoor/main.go:42 +0x93`
经测试数据库是正常的，可能原因为升级镜像导致的问题，请教如何处理。

**Comment by hsluoyz** [comment]
@lywlbk change all to English

**Comment by lywlbk** [comment]
> @lywlbk change all to English
Thank you, it has been modified to because

**Comment by hsluoyz** [comment]
@lywlbk how to reproduce this issue?

**Comment by zhoujunlingla** [comment]
I didn't find this problem when running with docker
![image](https://github.com/user-attachments/assets/43a4c899-072c-4db4-8631-57c4c58baa62)
![image](https://github.com/user-attachments/assets/6d2cfba5-5ee4-47bf-8085-459e05ee428c)

**Comment by hsluoyz** [comment]
@lywlbk a possible solution is: https://github.com/casdoor/casdoor/pull/4336 if you need
