### ISSUE TITLE
sqlite file dont created

### ISSUE THREAD

**Issue by unclesamwk** [casdoor/casdoor#3424]
Hey,

when i start the container like this:

```
docker run \
  -e driverName=sqlite \
  -e dataSourceName='file:casdoor.db?cache=shared' \
  -p 8000:8000 \
  casbin/casdoor:latest
```

i get following error:
```
panic: unable to open database file: out of memory (14)

goroutine 1 [running]:
github.com/casdoor/casdoor/object.(*Ormer).createTable(0xc000a0d340)
        /go/src/casdoor/object/ormer.go:293 +0xaa5
github.com/casdoor/casdoor/object.CreateTables()
        /go/src/casdoor/object/ormer.go:114 +0x3a
main.main()
        /go/src/casdoor/main.go:36 +0x35
```

it seems like the sqlite file dont be created by casdoor.

greetings
Sam

**Comment by unclesamwk** [comment]
Fix: dataSourceName='file:/conf/casdoor.db?cache=shared' <- fullpath
