### ISSUE TITLE
Cannot use multiples instances in kubernetes deployment for load balance

### ISSUE THREAD

**Issue by lrojas89** [casdoor/casdoor#3425]
Cannot use multiples instances in kubernetes deployment because i get a error 

`panic: pq: duplicate key value violates unique constraint "pg_class_relname_nsp_index"

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
        /go/src/casdoor/authz/authz.go:32 +0x139
main.main()
        /go/src/casdoor/main.go:42 +0x93`

and the session of user admin after a basic install get 403 forbiden after login 

i looking for a solution and found the next entry en [stackoverflow](https://stackoverflow.com/questions/74261789/postgres-create-table-if-not-exists-%E2%87%92-23505)

I used a Postgres v16 and casdoor v1.770.0 docker image

If i use a single replica it work, but if i use a 3 replicas i get the above behavior.

**Comment by lrojas89** [comment]
After some tests i get this error

`r
panic: pq: relation "IDX_casbin_api_rule_v2" already exists

goroutine 1 [running]:
github.com/casdoor/casdoor/authz.InitApi()
        /go/src/casdoor/authz/authz.go:32 +0x139
main.main()
        /go/src/casdoor/main.go:42 +0x93` 

I seems that the system try to reinstall the database, I guess it shouldn't happen

**Comment by hsluoyz** [comment]
@lrojas89 how to reproduce this error: `panic: pq: relation "IDX_casbin_api_rule_v2" already exists`?

**Comment by lrojas89** [comment]
> @lrojas89 how to reproduce this error: `panic: pq: relation "IDX_casbin_api_rule_v2" already exists`?

I install casdoor in k8s cluster, in deployment i use a postgres 16 as database backend, and  configure  a 1 replica, later i configure a hpa and set minReplicas: 3 and maxReplicas: 10. When other instances of pods initiate i get CrashLoopBackOff in some pods.

**Comment by IngwiePhoenix** [comment]
Your idea is good - but flawed. When setting three replicas of a simple Postgres container, you aren't clustering them. So, if you want to scale Casdoor, you need to split the two.

- You can run multiple instances of Casdoor
- You must set up either a single or a cluster of Postgres instances.

That said, I don't know if Casdoor actually supports that - does it utilize locking etc.? If not, you might not be able to... so it kinda depends on Casdoor's implementation.

**Comment by hsluoyz** [comment]
@lrojas89 @IngwiePhoenix Casdoor can be deployed in a multi-node mode. They can just share the same DB like MySQL

**Comment by lrojas89** [comment]
@hsluoyz The issue is with the redis cache server for captcha, because if you have more than 1 instance the captha code that generate in one of them is not the same in other, and because of that you can get error when you are redirected to other instance.

**Comment by hsluoyz** [comment]
@lrojas89 not only captcha is stateful, but also MFA maybe. You need to prove that it's valuable to put many efforts to make Casdoor fully stateless
