### ISSUE TITLE
Frequent Webhook panics

### ISSUE THREAD

**Issue by adamwoolhether** [casdoor/casdoor#684]
This happens randomly, both running locally or via Docker image.

Seems to happen more often if i don't interact with UI for a while, and come back.

```
goroutine 12 [running]:
github.com/casdoor/casdoor/object.getWebhooksByOrganization({0xc0004f03f0, 0x8})
	/Users/adam/go/src/casbin/casdoor/object/webhook.go:80 +0x118
github.com/casdoor/casdoor/object.SendWebhooks(0xc0001889a0)
	/Users/adam/go/src/casbin/casdoor/object/record.go:146 +0x2d
github.com/casdoor/casdoor/object.AddRecord(0xc0001889a0)
	/Users/adam/go/src/casbin/casdoor/object/record.go:89 +0x95
created by github.com/casdoor/casdoor/routers.RecordMessage
	/Users/adam/go/src/casbin/casdoor/routers/record.go:68 +0x118
```

Please let me know what other info i can provide to help.

**Comment by akkuman** [comment]
more error detail?
