### ISSUE TITLE
yarn start  failed

### ISSUE THREAD

**Issue by DjokerR** [casdoor/casdoor#792]
yarn run v1.22.19
casdoor v1.54.9
warning ../../package.json: No license field
$ cross-env PORT=7001 craco start
(node:37044) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /opt/app/casdoor/web/node_modules/postcss-safe-parser/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
ℹ ｢wds｣: Project is running at http://192.168.129.10/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /opt/app/casdoor/web/public
ℹ ｢wds｣: 404s will fallback to /

Starting the development server...

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/opt/app/casdoor/web/public'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2264:34)
    at createFsWatchInstance (/opt/app/casdoor/web/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/opt/app/casdoor/web/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/opt/app/casdoor/web/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/opt/app/casdoor/web/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/opt/app/casdoor/web/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/opt/app/casdoor/web/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqCallback.oncomplete (node:fs:199:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/opt/app/casdoor/web/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/opt/app/casdoor/web/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/opt/app/casdoor/web/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (node:fs:199:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/opt/app/casdoor/web/public',
  filename: '/opt/app/casdoor/web/public'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
****

**Comment by hsluoyz** [comment]
@DjokerR this is a Nodejs +Linux common issue, not Casdoor's issue. After some googling, you could find info like: https://stackoverflow.com/questions/63142518/system-limit-for-number-of-file-watchers-reached
